#
# Kaizen Theme Definitions
#

# --- Helper to define a theme structure ---
def define_theme(light_palette, dark_palette):
    """A simple helper to ensure themes have a consistent structure."""
    return {"light": light_palette, "dark": dark_palette}

# --- Theme Definitions ---
# All themes are now consolidated here in a single, consistent format.

THEMES = {
    # --- Original Themes ---
    "Tokyo Drift": define_theme(
        # Light Mode Palette
        {
            "--accent-color": "#89b4fa",
            "--bg": "#eff1f5",
            "--fg": "#4c4f69",
            "--fg-subtle": "#6c6f85",
            "--border": "#bcc0cc",
            "--canvas-inset": "#ccd0da",
            "--heatmap-color": "#89b4fa",
            "--heatmap-color-zero": "#ccd0da",
            "--icon-color": "#6c6f85",
            "--icon-color-filtered": "#89b4fa",
            "--highlight-bg": "#ccd0da",
            "--star-color": "#89b4fa",
            "--empty-star-color": "#6c6f85",
        },
        # Dark Mode Palette
        {
            "--accent-color": "#89b4fa",
            "--bg": "#1e1e2e",
            "--fg": "#cdd6f4",
            "--fg-subtle": "#a6adc8",
            "--border": "#45475a",
            "--canvas-inset": "#313244",
            "--heatmap-color": "#89b4fa",
            "--heatmap-color-zero": "#313244",
            "--icon-color": "#a6adc8",
            "--icon-color-filtered": "#89b4fa",
            "--highlight-bg": "#313244",
            "--star-color": "#89b4fa",
            "--empty-star-color": "#a6adc8",
        }
    ),
    "Gundam Wing": define_theme(
        # Light Mode Palette
        {
            "--accent-color": "#4285f4",
            "--bg": "#ffffff",
            "--fg": "#202124",
            "--fg-subtle": "#5f6368",
            "--border": "#dadce0",
            "--canvas-inset": "#f1f3f4",
            "--heatmap-color": "#4285f4",
            "--heatmap-color-zero": "#f1f3f4",
            "--icon-color": "#5f6368",
            "--icon-color-filtered": "#4285f4",
            "--highlight-bg": "#f1f3f4",
            "--star-color": "#4285f4",
            "--empty-star-color": "#5f6368",
        },
        # Dark Mode Palette
        {
            "--accent-color": "#8ab4f8",
            "--bg": "#202124",
            "--fg": "#e8eaed",
            "--fg-subtle": "#969ba1",
            "--border": "#5f6368",
            "--canvas-inset": "#3c4043",
            "--heatmap-color": "#8ab4f8",
            "--heatmap-color-zero": "#3c4043",
            "--icon-color": "#969ba1",
            "--icon-color-filtered": "#8ab4f8",
            "--highlight-bg": "#3c4043",
            "--star-color": "#8ab4f8",
            "--empty-star-color": "#969ba1",
        }
    ),
    "Mononoke": define_theme(
        # Light Mode Palette
        {
            "--accent-color": "#84a07c",
            "--bg": "#f4f1e8",
            "--fg": "#5a5449",
            "--fg-subtle": "#777164",
            "--border": "#e4e1d8",
            "--canvas-inset": "#e9e6dd",
            "--heatmap-color": "#84a07c",
            "--heatmap-color-zero": "#e9e6dd",
            "--icon-color": "#777164",
            "--icon-color-filtered": "#84a07c",
            "--highlight-bg": "#e9e6dd",
            "--star-color": "#84a07c",
            "--empty-star-color": "#777164",
        },
        # Dark Mode Palette
        {
            "--accent-color": "#84a07c",
            "--bg": "#242822",
            "--fg": "#e4e1d8",
            "--fg-subtle": "#a4a198",
            "--border": "#444842",
            "--canvas-inset": "#343832",
            "--heatmap-color": "#84a07c",
            "--heatmap-color-zero": "#343832",
            "--icon-color": "#a4a198",
            "--icon-color-filtered": "#84a07c",
            "--highlight-bg": "#343832",
            "--star-color": "#84a07c",
            "--empty-star-color": "#a4a198",
        }
    ),
    "Vendetta": define_theme(
        # Light Mode Palette
        {
            "--accent-color": "#e06c75",
            "--bg": "#f2f2f2",
            "--fg": "#282c34",
            "--fg-subtle": "#5c6370",
            "--border": "#dcdfe4",
            "--canvas-inset": "#e8e8e8",
            "--heatmap-color": "#e06c75",
            "--heatmap-color-zero": "#e8e8e8",
            "--icon-color": "#5c6370",
            "--icon-color-filtered": "#e06c75",
            "--highlight-bg": "#e8e8e8",
            "--star-color": "#e06c75",
            "--empty-star-color": "#5c6370",
        },
        # Dark Mode Palette
        {
            "--accent-color": "#e06c75",
            "--bg": "#21252b",
            "--fg": "#abb2bf",
            "--fg-subtle": "#5c6370",
            "--border": "#3b4048",
            "--canvas-inset": "#282c34",
            "--heatmap-color": "#e06c75",
            "--heatmap-color-zero": "#282c34",
            "--icon-color": "#5c6370",
            "--icon-color-filtered": "#e06c75",
            "--highlight-bg": "#282c34",
            "--star-color": "#e06c75",
            "--empty-star-color": "#5c6370",
        }
    ),

    # --- Catppuccin Themes ---
    "Catppuccin Latte": define_theme(
        {
            "--accent-color": "#1e66f5",
            "--bg": "#eff1f5",
            "--fg": "#4c4f69",
            "--fg-subtle": "#6c6f85",
            "--border": "#bcc0cc",
            "--canvas-inset": "#e6e9ef",
            "--heatmap-color": "#1e66f5",
            "--heatmap-color-zero": "#ccd0da",
            "--icon-color": "#7c7f93",
            "--icon-color-filtered": "#1e66f5",
            "--highlight-bg": "#ccd0da",
            "--star-color": "#1e66f5",
            "--empty-star-color": "#7c7f93",
        },
        # Latte is a light theme, so its "dark" mode is identical.
        {
            "--accent-color": "#1e66f5",
            "--bg": "#eff1f5",
            "--fg": "#4c4f69",
            "--fg-subtle": "#6c6f85",
            "--border": "#bcc0cc",
            "--canvas-inset": "#e6e9ef",
            "--heatmap-color": "#1e66f5",
            "--heatmap-color-zero": "#ccd0da",
            "--icon-color": "#7c7f93",
            "--icon-color-filtered": "#1e66f5",
            "--highlight-bg": "#ccd0da",
            "--star-color": "#1e66f5",
            "--empty-star-color": "#7c7f93",
        }
    ),
    "Catppuccin Frappé": define_theme(
        # Light mode counterpart for Frappe
        {
            "--accent-color": "#8caaee",
            "--bg": "#e6e9ef",
            "--fg": "#5c5f77",
            "--fg-subtle": "#6c6f85",
            "--border": "#9ca0b0",
            "--canvas-inset": "#ccd0da",
            "--heatmap-color": "#8caaee",
            "--heatmap-color-zero": "#bcc0cc",
            "--icon-color": "#6c6f85",
            "--icon-color-filtered": "#8caaee",
            "--highlight-bg": "#ccd0da",
            "--star-color": "#8caaee",
            "--empty-star-color": "#6c6f85",
        },
        {
            "--accent-color": "#ca9ee6",
            "--bg": "#303446",
            "--fg": "#c6d0f5",
            "--fg-subtle": "#a1a8c8",
            "--border": "#51576d",
            "--canvas-inset": "#292c3c",
            "--heatmap-color": "#8caaee",
            "--heatmap-color-zero": "#414559",
            "--icon-color": "#949cbb",
            "--icon-color-filtered": "#8caaee",
            "--highlight-bg": "#414559",
            "--star-color": "#ca9ee6",
            "--empty-star-color": "#949cbb",
        }
    ),
    "Catppuccin Macchiato": define_theme(
        # Light mode counterpart for Macchiato
        {
            "--accent-color": "#8aadf4",
            "--bg": "#e6e9ef",
            "--fg": "#4c4f69",
            "--fg-subtle": "#5c5f77",
            "--border": "#9ca0b0",
            "--canvas-inset": "#ccd0da",
            "--heatmap-color": "#8aadf4",
            "--heatmap-color-zero": "#bcc0cc",
            "--icon-color": "#6c6f85",
            "--icon-color-filtered": "#8aadf4",
            "--highlight-bg": "#ccd0da",
            "--star-color": "#8aadf4",
            "--empty-star-color": "#6c6f85",
        },
        {
            "--accent-color": "#f5bde6",
            "--bg": "#24273a",
            "--fg": "#cad3f5",
            "--fg-subtle": "#a5adce",
            "--border": "#494d64",
            "--canvas-inset": "#1e2030",
            "--heatmap-color": "#8aadf4",
            "--heatmap-color-zero": "#363a4f",
            "--icon-color": "#939ab7",
            "--icon-color-filtered": "#8aadf4",
            "--highlight-bg": "#363a4f",
            "--star-color": "#f5bde6",
            "--empty-star-color": "#939ab7",
        }
    ),
    "Catppuccin Mocha": define_theme(
        # Light mode counterpart for Mocha
        {
            "--accent-color": "#89b4fa",
            "--bg": "#ccd0da",
            "--fg": "#4c4f69",
            "--fg-subtle": "#5c5f77",
            "--border": "#9ca0b0",
            "--canvas-inset": "#bcc0cc",
            "--heatmap-color": "#89b4fa",
            "--heatmap-color-zero": "#bcc0cc",
            "--icon-color": "#6c6f85",
            "--icon-color-filtered": "#89b4fa",
            "--highlight-bg": "#bcc0cc",
            "--star-color": "#89b4fa",
            "--empty-star-color": "#6c6f85",
        },
        {
            "--accent-color": "#b4befe",
            "--bg": "#1e1e2e",
            "--fg": "#cdd6f4",
            "--fg-subtle": "#bac2de",
            "--border": "#6c7086",
            "--canvas-inset": "#181825",
            "--heatmap-color": "#89b4fa",
            "--heatmap-color-zero": "#313244",
            "--icon-color": "#9399b2",
            "--icon-color-filtered": "#89b4fa",
            "--highlight-bg": "#313244",
            "--star-color": "#b4befe",
            "--empty-star-color": "#9399b2",
        }
    ),

    # --- Community Themes ---
    "Rosé Pine": define_theme(
        {
            "--accent-color": "#907aa9",
            "--bg": "#faf4ed",
            "--fg": "#575279",
            "--fg-subtle": "#797593",
            "--border": "#d4d1e2",
            "--canvas-inset": "#f2f0f7",
            "--heatmap-color": "#907aa9",
            "--heatmap-color-zero": "#e4e1d8",
            "--icon-color": "#797593",
            "--icon-color-filtered": "#907aa9",
            "--highlight-bg": "#f2f0f7",
            "--star-color": "#907aa9",
            "--empty-star-color": "#797593",
        },
        {
            "--accent-color": "#c4a7e7",
            "--bg": "#191724",
            "--fg": "#e0def4",
            "--fg-subtle": "#908caa",
            "--border": "#403d52",
            "--canvas-inset": "#1f1d2e",
            "--heatmap-color": "#c4a7e7",
            "--heatmap-color-zero": "#26233a",
            "--icon-color": "#908caa",
            "--icon-color-filtered": "#c4a7e7",
            "--highlight-bg": "#26233a",
            "--star-color": "#c4a7e7",
            "--empty-star-color": "#908caa",
        }
    ),
    "Nord": define_theme(
        {
            "--accent-color": "#5E81AC",
            "--bg": "#ECEFF4",
            "--fg": "#2E3440",
            "--fg-subtle": "#4C566A",
            "--border": "#D8DEE9",
            "--canvas-inset": "#E5E9F0",
            "--heatmap-color": "#5E81AC",
            "--heatmap-color-zero": "#D8DEE9",
            "--icon-color": "#4C566A",
            "--icon-color-filtered": "#5E81AC",
            "--highlight-bg": "#E5E9F0",
            "--star-color": "#5E81AC",
            "--empty-star-color": "#4C566A",
        },
        {
            "--accent-color": "#88C0D0",
            "--bg": "#2E3440",
            "--fg": "#ECEFF4",
            "--fg-subtle": "#D8DEE9",
            "--border": "#434C5E",
            "--canvas-inset": "#3B4252",
            "--heatmap-color": "#88C0D0",
            "--heatmap-color-zero": "#3B4252",
            "--icon-color": "#D8DEE9",
            "--icon-color-filtered": "#88C0D0",
            "--highlight-bg": "#3B4252",
            "--star-color": "#88C0D0",
            "--empty-star-color": "#D8DEE9",
        }
    ),
    "Dracula": define_theme(
        {
            "--accent-color": "#bd93f9",
            "--bg": "#F8F8F2",
            "--fg": "#282A36",
            "--fg-subtle": "#6272A4",
            "--border": "#E6E6E6",
            "--canvas-inset": "#F1F1F1",
            "--heatmap-color": "#bd93f9",
            "--heatmap-color-zero": "#E6E6E6",
            "--icon-color": "#6272A4",
            "--icon-color-filtered": "#bd93f9",
            "--highlight-bg": "#F1F1F1",
            "--star-color": "#bd93f9",
            "--empty-star-color": "#6272A4",
        },
        {
            "--accent-color": "#ff79c6",
            "--bg": "#282a36",
            "--fg": "#f8f8f2",
            "--fg-subtle": "#6272a4",
            "--border": "#44475a",
            "--canvas-inset": "#21222C",
            "--heatmap-color": "#ff79c6",
            "--heatmap-color-zero": "#44475a",
            "--icon-color": "#f1fa8c",
            "--icon-color-filtered": "#ff79c6",
            "--highlight-bg": "#44475a",
            "--star-color": "#ff79c6",
            "--empty-star-color": "#6272a4",
        }
    ),

    # --- First batch of User-Requested Themes ---
    "Tartan": define_theme(
        # Light Mode Palette
        {
            "--accent-color": "#e86a33",
            "--bg": "#fdf8f4",
            "--fg": "#3b2b23",
            "--fg-subtle": "#8f6754",
            "--border": "#e8e1da",
            "--canvas-inset": "#f5efe9",
            "--heatmap-color": "#e86a33",
            "--heatmap-color-zero": "#f5efe9",
            "--icon-color": "#8f6754",
            "--icon-color-filtered": "#e86a33",
            "--highlight-bg": "#f5efe9",
            "--star-color": "#e86a33",
            "--empty-star-color": "#8f6754",
        },
        # Dark Mode Palette
        {
            "--accent-color": "#e86a33",
            "--bg": "#3b2b23",
            "--fg": "#f5dcc4",
            "--fg-subtle": "#b18c78",
            "--border": "#584236",
            "--canvas-inset": "#4a362b",
            "--heatmap-color": "#e86a33",
            "--heatmap-color-zero": "#4a362b",
            "--icon-color": "#b18c78",
            "--icon-color-filtered": "#e86a33",
            "--highlight-bg": "#4a362b",
            "--star-color": "#e86a33",
            "--empty-star-color": "#b18c78",
        }
    ),
    "Muad'Dib": define_theme(
        # Light Mode Palette
        {
            "--accent-color": "#4c86c1",
            "--bg": "#c4b78f",
            "--fg": "#3e271f",
            "--fg-subtle": "#6e4a3c",
            "--border": "#ada17b",
            "--canvas-inset": "#b8ab85",
            "--heatmap-color": "#4c86c1",
            "--heatmap-color-zero": "#b8ab85",
            "--icon-color": "#6e4a3c",
            "--icon-color-filtered": "#4c86c1",
            "--highlight-bg": "#b8ab85",
            "--star-color": "#4c86c1",
            "--empty-star-color": "#6e4a3c",
        },
        # Dark Mode Palette
        {
            "--accent-color": "#4c86c1",
            "--bg": "#2a3231",
            "--fg": "#e8d573",
            "--fg-subtle": "#c4b78f",
            "--border": "#434d4c",
            "--canvas-inset": "#343d3c",
            "--heatmap-color": "#4c86c1",
            "--heatmap-color-zero": "#343d3c",
            "--icon-color": "#c4b78f",
            "--icon-color-filtered": "#4c86c1",
            "--highlight-bg": "#343d3c",
            "--star-color": "#4c86c1",
            "--empty-star-color": "#c4b78f",
        }
    ),
    "Sanrio": define_theme(
        # Light Mode Palette
        {
            "--accent-color": "#e4a8be",
            "--bg": "#ffffff",
            "--fg": "#5b6175",
            "--fg-subtle": "#b3b8d6",
            "--border": "#e1e4f0",
            "--canvas-inset": "#f4f6fa",
            "--heatmap-color": "#e4a8be",
            "--heatmap-color-zero": "#f4f6fa",
            "--icon-color": "#b3b8d6",
            "--icon-color-filtered": "#e4a8be",
            "--highlight-bg": "#f4f6fa",
            "--star-color": "#e4a8be",
            "--empty-star-color": "#b3b8d6",
        },
        # Dark Mode Palette
        {
            "--accent-color": "#e4a8be",
            "--bg": "#3c3f58",
            "--fg": "#d4e1cb",
            "--fg-subtle": "#a4a8c1",
            "--border": "#555976",
            "--canvas-inset": "#484c69",
            "--heatmap-color": "#e4a8be",
            "--heatmap-color-zero": "#484c69",
            "--icon-color": "#a4a8c1",
            "--icon-color-filtered": "#e4a8be",
            "--highlight-bg": "#484c69",
            "--star-color": "#e4a8be",
            "--empty-star-color": "#a4a8c1",
        }
    ),
    "Wonder": define_theme(
        # Light Mode Palette
        {
            "--accent-color": "#5d6efc",
            "--bg": "#f5ede5",
            "--fg": "#292523",
            "--fg-subtle": "#6a6360",
            "--border": "#e0d4ca",
            "--canvas-inset": "#ebe0d6",
            "--heatmap-color": "#5d6efc",
            "--heatmap-color-zero": "#ebe0d6",
            "--icon-color": "#6a6360",
            "--icon-color-filtered": "#5d6efc",
            "--highlight-bg": "#ebe0d6",
            "--star-color": "#5d6efc",
            "--empty-star-color": "#6a6360",
        },
        # Dark Mode Palette
        {
            "--accent-color": "#5d6efc",
            "--bg": "#292523",
            "--fg": "#f5ede5",
            "--fg-subtle": "#9a938f",
            "--border": "#413b38",
            "--canvas-inset": "#3a3533",
            "--heatmap-color": "#5d6efc",
            "--heatmap-color-zero": "#3a3533",
            "--icon-color": "#9a938f",
            "--icon-color-filtered": "#5d6efc",
            "--highlight-bg": "#3a3533",
            "--star-color": "#5d6efc",
            "--empty-star-color": "#9a938f",
        }
    ),
    "Everforest": define_theme(
        # Light Mode Palette (Hard)
        {
            "--accent-color": "#6791C9",
            "--bg": "#fdf6e3",
            "--fg": "#5c6a72",
            "--fg-subtle": "#928374",
            "--border": "#d5c4a1",
            "--canvas-inset": "#f2e5bc",
            "--heatmap-color": "#6791C9",
            "--heatmap-color-zero": "#f2e5bc",
            "--icon-color": "#928374",
            "--icon-color-filtered": "#6791C9",
            "--highlight-bg": "#f2e5bc",
            "--star-color": "#6791C9",
            "--empty-star-color": "#928374",
        },
        # Dark Mode Palette (Hard)
        {
            "--accent-color": "#7fbbb3",
            "--bg": "#2e2e3c",
            "--fg": "#d1c7a1",
            "--fg-subtle": "#a89984",
            "--border": "#4e4e5a",
            "--canvas-inset": "#3a3a4a",
            "--heatmap-color": "#7fbbb3",
            "--heatmap-color-zero": "#3a3a4a",
            "--icon-color": "#a89984",
            "--icon-color-filtered": "#7fbbb3",
            "--highlight-bg": "#3a3a4a",
            "--star-color": "#7fbbb3",
            "--empty-star-color": "#a89984",
        }
    ),

    # --- Second batch of User-Requested Themes ---
    "Machiatto": define_theme(
        {
            "--accent-color": "#8A6B5C",
            "--bg": "#F0E7D5",
            "--fg": "#4B3935",
            "--fg-subtle": "#7E6A60",
            "--border": "#D9CCA5",
            "--canvas-inset": "#E6DBC5",
            "--heatmap-color": "#8A6B5C",
            "--heatmap-color-zero": "#E6DBC5",
            "--icon-color": "#7E6A60",
            "--icon-color-filtered": "#8A6B5C",
            "--highlight-bg": "#E6DBC5",
            "--star-color": "#8A6B5C",
            "--empty-star-color": "#7E6A60",
        },
        {
            "--accent-color": "#D4C3A3",
            "--bg": "#4B3935",
            "--fg": "#F0E7D5",
            "--fg-subtle": "#B3A48A",
            "--border": "#6D534A",
            "--canvas-inset": "#5C4640",
            "--heatmap-color": "#D4C3A3",
            "--heatmap-color-zero": "#5C4640",
            "--icon-color": "#B3A48A",
            "--icon-color-filtered": "#D4C3A3",
            "--highlight-bg": "#5C4640",
            "--star-color": "#D4C3A3",
            "--empty-star-color": "#B3A48A",
        }
    ),
    "Pistache": define_theme(
        {
            "--accent-color": "#7A8450",
            "--bg": "#F8EFDA",
            "--fg": "#4D562D",
            "--fg-subtle": "#6A7347",
            "--border": "#E2D9C0",
            "--canvas-inset": "#ECE4CE",
            "--heatmap-color": "#7A8450",
            "--heatmap-color-zero": "#ECE4CE",
            "--icon-color": "#6A7347",
            "--icon-color-filtered": "#7A8450",
            "--highlight-bg": "#ECE4CE",
            "--star-color": "#7A8450",
            "--empty-star-color": "#6A7347",
        },
        {
            "--accent-color": "#7A8450",
            "--bg": "#343A22",
            "--fg": "#F8EFDA",
            "--fg-subtle": "#BFC69B",
            "--border": "#565D43",
            "--canvas-inset": "#4A5135",
            "--heatmap-color": "#7A8450",
            "--heatmap-color-zero": "#4A5135",
            "--icon-color": "#BFC69B",
            "--icon-color-filtered": "#7A8450",
            "--highlight-bg": "#4A5135",
            "--star-color": "#7A8450",
            "--empty-star-color": "#BFC69B",
        }
    ),
    "Butter": define_theme(
        {
            "--accent-color": "#916D45",
            "--bg": "#FFEED2",
            "--fg": "#916D45",
            "--fg-subtle": "#A88E6A",
            "--border": "#E9D8BE",
            "--canvas-inset": "#F2E3CA",
            "--heatmap-color": "#916D45",
            "--heatmap-color-zero": "#F2E3CA",
            "--icon-color": "#A88E6A",
            "--icon-color-filtered": "#916D45",
            "--highlight-bg": "#F2E3CA",
            "--star-color": "#916D45",
            "--empty-star-color": "#A88E6A",
        },
        {
            "--accent-color": "#B59368",
            "--bg": "#3D2F1D",
            "--fg": "#FFEED2",
            "--fg-subtle": "#DDCAB2",
            "--border": "#62503A",
            "--canvas-inset": "#51412A",
            "--heatmap-color": "#B59368",
            "--heatmap-color-zero": "#51412A",
            "--icon-color": "#DDCAB2",
            "--icon-color-filtered": "#B59368",
            "--highlight-bg": "#51412A",
            "--star-color": "#B59368",
            "--empty-star-color": "#DDCAB2",
        }
    ),
    "Tiger Taro": define_theme(
        {
            "--accent-color": "#C8C3FF",
            "--bg": "#FFF0E1",
            "--fg": "#5B5791",
            "--fg-subtle": "#8582B3",
            "--border": "#E4D9CE",
            "--canvas-inset": "#EEE5DB",
            "--heatmap-color": "#C8C3FF",
            "--heatmap-color-zero": "#EEE5DB",
            "--icon-color": "#8582B3",
            "--icon-color-filtered": "#C8C3FF",
            "--highlight-bg": "#EEE5DB",
            "--star-color": "#C8C3FF",
            "--empty-star-color": "#8582B3",
        },
        {
            "--accent-color": "#C8C3FF",
            "--bg": "#3D3B5C",
            "--fg": "#FFF0E1",
            "--fg-subtle": "#D6D4F5",
            "--border": "#5C5A7D",
            "--canvas-inset": "#4E4C6E",
            "--heatmap-color": "#C8C3FF",
            "--heatmap-color-zero": "#4E4C6E",
            "--icon-color": "#D6D4F5",
            "--icon-color-filtered": "#C8C3FF",
            "--highlight-bg": "#4E4C6E",
            "--star-color": "#C8C3FF",
            "--empty-star-color": "#D6D4F5",
        }
    ),
    "Lavander": define_theme(
        {
            "--accent-color": "#9187F5",
            "--bg": "#DCE1F0",
            "--fg": "#000541",
            "--fg-subtle": "#4D5087",
            "--border": "#C2C8D9",
            "--canvas-inset": "#CCD2E3",
            "--heatmap-color": "#9187F5",
            "--heatmap-color-zero": "#CCD2E3",
            "--icon-color": "#4D5087",
            "--icon-color-filtered": "#9187F5",
            "--highlight-bg": "#CCD2E3",
            "--star-color": "#9187F5",
            "--empty-star-color": "#4D5087",
        },
        {
            "--accent-color": "#9187F5",
            "--bg": "#000541",
            "--fg": "#DCE1F0",
            "--fg-subtle": "#A6A9D9",
            "--border": "#2E3167",
            "--canvas-inset": "#171A54",
            "--heatmap-color": "#9187F5",
            "--heatmap-color-zero": "#171A54",
            "--icon-color": "#A6A9D9",
            "--icon-color-filtered": "#9187F5",
            "--highlight-bg": "#171A54",
            "--star-color": "#9187F5",
            "--empty-star-color": "#A6A9D9",
        }
    ),
    "Mint": define_theme(
        {
            "--accent-color": "#76C0AF",
            "--bg": "#DDE5ED",
            "--fg": "#25282A",
            "--fg-subtle": "#6C7378",
            "--border": "#C4CDD6",
            "--canvas-inset": "#C4CDD6",
            "--heatmap-color": "#76C0AF",
            "--heatmap-color-zero": "#C4CDD6",
            "--icon-color": "#6C7378",
            "--icon-color-filtered": "#76C0AF",
            "--highlight-bg": "#C4CDD6",
            "--star-color": "#76C0AF",
            "--empty-star-color": "#6C7378",
        },
        {
            "--accent-color": "#A7E6D7",
            "--bg": "#25282A",
            "--fg": "#DDE5ED",
            "--fg-subtle": "#A7B0B8",
            "--border": "#4C5052",
            "--canvas-inset": "#36393B",
            "--heatmap-color": "#A7E6D7",
            "--heatmap-color-zero": "#36393B",
            "--icon-color": "#A7B0B8",
            "--icon-color-filtered": "#A7E6D7",
            "--highlight-bg": "#36393B",
            "--star-color": "#A7E6D7",
            "--empty-star-color": "#A7B0B8",
        }
    ),
    "Aux Bluets": define_theme(
        {
            "--accent-color": "#2F4B8A",
            "--bg": "#F7F2E9",
            "--fg": "#2F4B8A",
            "--fg-subtle": "#5F74A8",
            "--border": "#DBD5CA",
            "--canvas-inset": "#EAE4D9",
            "--heatmap-color": "#2F4B8A",
            "--heatmap-color-zero": "#EAE4D9",
            "--icon-color": "#5F74A8",
            "--icon-color-filtered": "#2F4B8A",
            "--highlight-bg": "#EAE4D9",
            "--star-color": "#2F4B8A",
            "--empty-star-color": "#5F74A8",
        },
        {
            "--accent-color": "#5F7BC2",
            "--bg": "#1E315A",
            "--fg": "#F7F2E9",
            "--fg-subtle": "#C9D1E4",
            "--border": "#3B4E7A",
            "--canvas-inset": "#2A3C6A",
            "--heatmap-color": "#5F7BC2",
            "--heatmap-color-zero": "#2A3C6A",
            "--icon-color": "#C9D1E4",
            "--icon-color-filtered": "#5F7BC2",
            "--highlight-bg": "#2A3C6A",
            "--star-color": "#5F7BC2",
            "--empty-star-color": "#C9D1E4",
        }
    ),
    "Blueberry": define_theme(
        {
            "--accent-color": "#4B67A4",
            "--bg": "#D4DAE8",
            "--fg": "#2D3B5A",
            "--fg-subtle": "#6A7899",
            "--border": "#BFC5D6",
            "--canvas-inset": "#C8CEDD",
            "--heatmap-color": "#4B67A4",
            "--heatmap-color-zero": "#C8CEDD",
            "--icon-color": "#6A7899",
            "--icon-color-filtered": "#4B67A4",
            "--highlight-bg": "#C8CEDD",
            "--star-color": "#4B67A4",
            "--empty-star-color": "#6A7899",
        },
        {
            "--accent-color": "#A9B8D9",
            "--bg": "#2D3B5A",
            "--fg": "#D4DAE8",
            "--fg-subtle": "#BFC5D6",
            "--border": "#49587C",
            "--canvas-inset": "#3A486A",
            "--heatmap-color": "#A9B8D9",
            "--heatmap-color-zero": "#3A486A",
            "--icon-color": "#BFC5D6",
            "--icon-color-filtered": "#A9B8D9",
            "--highlight-bg": "#3A486A",
            "--star-color": "#A9B8D9",
            "--empty-star-color": "#BFC5D6",
        }
    ),
    "Cris": define_theme(
        {
            "--accent-color": "#C85C42",
            "--bg": "#F9F0DF",
            "--fg": "#344660",
            "--fg-subtle": "#6B798F",
            "--border": "#E3DACE",
            "--canvas-inset": "#EDE5D5",
            "--heatmap-color": "#C85C42",
            "--heatmap-color-zero": "#EDE5D5",
            "--icon-color": "#6B798F",
            "--icon-color-filtered": "#C85C42",
            "--highlight-bg": "#EDE5D5",
            "--star-color": "#C85C42",
            "--empty-star-color": "#6B798F",
        },
        {
            "--accent-color": "#C85C42",
            "--bg": "#344660",
            "--fg": "#F9F0DF",
            "--fg-subtle": "#DCD3C1",
            "--border": "#536580",
            "--canvas-inset": "#41536D",
            "--heatmap-color": "#C85C42",
            "--heatmap-color-zero": "#41536D",
            "--icon-color": "#DCD3C1",
            "--icon-color-filtered": "#C85C42",
            "--highlight-bg": "#41536D",
            "--star-color": "#C85C42",
            "--empty-star-color": "#DCD3C1",
        }
    ),
    "Flowers": define_theme(
        {
            "--accent-color": "#D8A48F",
            "--bg": "#EFEBCE",
            "--fg": "#A3A380",
            "--fg-subtle": "#B8B8A0",
            "--border": "#D7CE93",
            "--canvas-inset": "#E2DDBA",
            "--heatmap-color": "#D8A48F",
            "--heatmap-color-zero": "#E2DDBA",
            "--icon-color": "#B8B8A0",
            "--icon-color-filtered": "#D8A48F",
            "--highlight-bg": "#E2DDBA",
            "--star-color": "#D8A48F",
            "--empty-star-color": "#B8B8A0",
        },
        {
            "--accent-color": "#BB8588",
            "--bg": "#4F4F3D",
            "--fg": "#EFEBCE",
            "--fg-subtle": "#D7CE93",
            "--border": "#7A7A5D",
            "--canvas-inset": "#64644D",
            "--heatmap-color": "#BB8588",
            "--heatmap-color-zero": "#64644D",
            "--icon-color": "#D7CE93",
            "--icon-color-filtered": "#BB8588",
            "--highlight-bg": "#64644D",
            "--star-color": "#BB8588",
            "--empty-star-color": "#D7CE93",
        }
    ),
}

