/*
    Onigiri Heatmap Renderer
    This script is responsible for drawing the heatmap graph based on review data,
    with different views for Year, Month, and Week.
*/

// Ensure the KaizenHeatmap object exists
window.KaizenHeatmap = window.KaizenHeatmap || {};

(function (exports) {
    "use strict";

    // --- STATE MANAGEMENT & CACHE ---
    let state = {
        view: 'year', // 'year', 'month', 'week'
        targetDate: new Date(),
    };


    // --- DATA PREPARATION ---
    function prepareData(rawData) {
        // Python now sends date keys (YYYY-MM-DD) directly.
        // These keys are already adjusted for local timezone and rollover.

        // Convert object from Python into a Map for easier lookup
        const reviewsByDay = new Map(Object.entries(rawData.calendar || {}));

        // Convert object from Python into a Map
        const duesByDay = new Map(Object.entries(rawData.due_calendar || {}));

        // Get today's date key from Python
        const todayKey = rawData.today_date_key;

        // Get daily average for relative scaling
        const dailyAverage = rawData.daily_average || 0;

        // No need to calculate offset or convert timestamps here.

        return { reviewsByDay, duesByDay, todayKey, dailyAverage };
    }

    // Classifies past review count into 8 levels (0-8) based on daily average
    function getIntensityLevel(count, dailyAverage) {
        if (count === 0) return 0;

        // Use a minimum average of 3 to avoid "1 review = max intensity" scenarios for new users
        const avg = Math.max(dailyAverage, 5);

        if (count < 0.4 * avg) return 1;
        if (count < 0.7 * avg) return 2;
        if (count < 1.0 * avg) return 3;
        if (count < 1.3 * avg) return 4;
        if (count < 1.6 * avg) return 5;
        if (count < 2.0 * avg) return 6;
        if (count < 2.5 * avg) return 7;

        // >= 2.5 * avg
        return 8;
    }

    // Classifies future due count into 8 levels (0-8) based on daily average (same scale)
    function getDueIntensityLevel(count, dailyAverage) {
        if (count === 0) return 0;

        const avg = Math.max(dailyAverage, 5);

        if (count < 0.4 * avg) return 1;
        if (count < 0.7 * avg) return 2;
        if (count < 1.0 * avg) return 3;
        if (count < 1.3 * avg) return 4;
        if (count < 1.6 * avg) return 5;
        if (count < 2.0 * avg) return 6;
        if (count < 2.5 * avg) return 7;

        return 8;
    }

    // --- HELPER FUNCTION ---

    /**
     * Formats a Date object into a YYYY-MM-DD string in its local timezone.
     * This is crucial to match the keys generated by Python.
     * @param {Date} date The input date object.
     * @returns {string} A string in "YYYY-MM-DD" format.
     */
    function getLocalDateKey(date) {
        const year = date.getFullYear();
        const month = (date.getMonth() + 1).toString().padStart(2, '0');
        const day = date.getDate().toString().padStart(2, '0');
        return `${year}-${month}-${day}`;
    }


    // --- VIEW RENDERERS ---

    function drawYearView(gridContainer, preparedData, config) {
        gridContainer.className = 'heatmap-grid year-view';
        gridContainer.dataset.monthsHidden = !config.heatmapShowMonths;
        gridContainer.dataset.weekdaysHidden = !config.heatmapShowWeekdays;

        const target = state.targetDate;
        const year = target.getFullYear();
        const firstDayOfYear = new Date(year, 0, 1);

        let html = `
            <div class="heatmap-months"></div>
            <div class="heatmap-weekdays"><div>M</div><div>T</div><div>W</div><div>T</div><div>F</div><div>S</div><div>S</div></div>
            <div class="heatmap-cells"></div>
        `;
        gridContainer.innerHTML = html;

        const cellsContainer = gridContainer.querySelector('.heatmap-cells');
        const monthsContainer = gridContainer.querySelector('.heatmap-months');
        let currentMonth = -1;

        for (let i = 0; i < 371; i++) {
            const dayOfWeek = (firstDayOfYear.getDay() + 6) % 7;
            const date = new Date(firstDayOfYear);
            date.setDate(firstDayOfYear.getDate() - dayOfWeek + i);

            if (date.getFullYear() !== year) {
                const emptyCell = document.createElement('div');
                emptyCell.className = 'heatmap-day-cell empty';
                cellsContainer.appendChild(emptyCell);
                continue;
            }

            if (date.getDate() === 1 && date.getMonth() !== currentMonth) {
                currentMonth = date.getMonth();
                const monthLabel = document.createElement('div');
                monthLabel.className = 'month-label';
                monthLabel.textContent = date.toLocaleString('default', { month: 'short' });
                monthLabel.style.gridColumn = Math.floor(i / 7) + 1;
                monthsContainer.appendChild(monthLabel);
            }

            const dateKey = getLocalDateKey(date); // FIX: Use local date key
            const reviewCount = preparedData.reviewsByDay.get(dateKey) || 0;
            const dueCount = preparedData.duesByDay.get(dateKey) || 0;
            const cell = createCell(date, reviewCount, dueCount, config, preparedData.todayKey, preparedData.dailyAverage);
            cellsContainer.appendChild(cell);
        }
    }

    function drawMonthView(gridContainer, preparedData, config) {
        gridContainer.className = 'heatmap-grid month-view';
        gridContainer.dataset.weekdaysHidden = !config.heatmapShowWeekdays;
        const target = state.targetDate;
        const year = target.getFullYear();
        const month = target.getMonth();
        const firstDayOfMonth = new Date(year, month, 1);

        let html = `
            <div class="month-weekdays-header"><div>Mon</div><div>Tue</div><div>Wed</div><div>Thu</div><div>Fri</div><div>Sat</div><div>Sun</div></div>
            <div class="month-cells-grid"></div>
        `;
        gridContainer.innerHTML = html;
        const cellsContainer = gridContainer.querySelector('.month-cells-grid');

        const firstDayOfWeek = (firstDayOfMonth.getDay() + 6) % 7;
        for (let i = 0; i < firstDayOfWeek; i++) {
            const emptyCell = document.createElement('div');
            emptyCell.className = 'heatmap-day-cell empty';
            cellsContainer.appendChild(emptyCell);
        }

        const lastDayOfMonth = new Date(year, month + 1, 0).getDate();
        for (let i = 1; i <= lastDayOfMonth; i++) {
            const date = new Date(year, month, i);
            const dateKey = getLocalDateKey(date); // FIX: Use local date key
            const reviewCount = preparedData.reviewsByDay.get(dateKey) || 0;
            const dueCount = preparedData.duesByDay.get(dateKey) || 0;
            const cell = createCell(date, reviewCount, dueCount, config, preparedData.todayKey, preparedData.dailyAverage);
            cellsContainer.appendChild(cell);
        }
    }

    function drawWeekView(gridContainer, preparedData, config) {
        gridContainer.className = 'heatmap-grid week-view';
        gridContainer.dataset.headerHidden = !config.heatmapShowWeekHeader;
        const target = state.targetDate;
        const startDate = new Date(target);
        const startDayOfWeek = (target.getDay() + 6) % 7;
        startDate.setDate(startDate.getDate() - startDayOfWeek);

        let html = `
            <div class="week-days-header"></div>
            <div class="week-cells-grid"></div>
        `;
        gridContainer.innerHTML = html;

        const headerContainer = gridContainer.querySelector('.week-days-header');
        const cellsContainer = gridContainer.querySelector('.week-cells-grid');

        for (let i = 0; i < 7; i++) {
            const date = new Date(startDate);
            date.setDate(startDate.getDate() + i);

            const header = document.createElement('div');
            header.innerHTML = `
                <div class="weekday-label">${date.toLocaleString('default', { weekday: 'short' })}</div>
                <div class="day-label">${date.getDate()}</div>
            `;
            headerContainer.appendChild(header);

            const dateKey = getLocalDateKey(date); // FIX: Use local date key
            const reviewCount = preparedData.reviewsByDay.get(dateKey) || 0;
            const dueCount = preparedData.duesByDay.get(dateKey) || 0;
            const cell = createCell(date, reviewCount, dueCount, config, preparedData.todayKey, preparedData.dailyAverage);
            cellsContainer.appendChild(cell);
        }
    }

    function createCell(date, reviewCount, dueCount, config, todayKey, dailyAverage) {
        const cell = document.createElement('div');
        cell.className = 'heatmap-day-cell';

        const dateKey = getLocalDateKey(date); // FIX: Use local date key
        let tooltipText;
        const dateText = date.toLocaleDateString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });

        if (dateKey === todayKey) {
            // --- TODAY ---
            // Mark today's cell with a special class
            cell.classList.add('today');

            // Set review count and level for proper coloring
            cell.dataset.reviewCount = reviewCount;
            cell.dataset.level = getIntensityLevel(reviewCount, dailyAverage);

            // Build tooltip with reviews done today
            tooltipText = `${reviewCount} review${reviewCount !== 1 ? 's' : ''} done today`;
        } else if (dateKey < todayKey) {
            // --- PAST ---
            cell.dataset.reviewCount = reviewCount;
            cell.dataset.level = getIntensityLevel(reviewCount, dailyAverage);
            tooltipText = `${reviewCount} review${reviewCount !== 1 ? 's' : ''} on ${dateText}`;
        } else {
            // --- FUTURE ---
            cell.classList.add('future-day');
            cell.dataset.dueCount = dueCount;
            cell.dataset.dueLevel = getDueIntensityLevel(dueCount, dailyAverage);

            const dueText = `${dueCount} review${dueCount !== 1 ? 's' : ''} due`;
            tooltipText = `${dueText} on ${dateText}`;
        }

        const shapeDiv = document.createElement('div');
        shapeDiv.className = 'day-shape';

        if (config.heatmapSvgContent) {
            const encodedSvg = encodeURIComponent(config.heatmapSvgContent);
            const dataUri = `url("data:image/svg+xml,${encodedSvg}")`;
            shapeDiv.style.webkitMaskImage = dataUri;
            shapeDiv.style.maskImage = dataUri;
            shapeDiv.style.webkitMaskSize = 'contain';
            shapeDiv.style.maskSize = 'contain';
            shapeDiv.style.webkitMaskRepeat = 'no-repeat';
            shapeDiv.style.maskRepeat = 'no-repeat';
            shapeDiv.style.webkitMaskPosition = '50% 50%';
            shapeDiv.style.maskPosition = '50% 50%';
        }
        cell.appendChild(shapeDiv);

        cell.setAttribute('data-tooltip', tooltipText);
        return cell;
    }

    // --- MAIN RENDER FUNCTION ---
    exports.render = function (containerId, data, config) {
        const container = document.getElementById(containerId);
        if (!container) return;

        const preparedData = prepareData(data);

        // Initialize view from config if available (defaulting to 'year' is handled by config.py/heatmap.py logic, but fallback here too)
        if (config.heatmapDefaultView) {
            state.view = config.heatmapDefaultView;
        }

        function draw() {
            const streakHTML = config.heatmapShowStreak ? `<div class="streak-counter">${data.streak} day streak</div>` : '';

            let navHTML = '';
            if (state.view === 'year') {
                navHTML = `
                    <button class="nav-btn" data-nav="-1"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640"><path d="M201.4 297.4C188.9 309.9 188.9 330.2 201.4 342.7L361.4 502.7C373.9 515.2 394.2 515.2 406.7 502.7C419.2 490.2 419.2 469.9 406.7 457.4L269.3 320L406.6 182.6C419.1 170.1 419.1 149.8 406.6 137.3C394.1 124.8 373.8 124.8 361.3 137.3L201.3 297.3z"/></svg></button>
                    <span class="nav-title">${state.targetDate.getFullYear()}</span>
                    <button class="nav-btn" data-nav="1"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640"><path d="M439.1 297.4C451.6 309.9 451.6 330.2 439.1 342.7L279.1 502.7C266.6 515.2 246.3 515.2 233.8 502.7C221.3 490.2 221.3 469.9 233.8 457.4L371.2 320L233.9 182.6C221.4 170.1 221.4 149.8 233.9 137.3C246.4 124.8 266.7 124.8 279.2 137.3L439.2 297.3z"/></svg></button>
                `;
            } else if (state.view === 'month') {
                navHTML = `
                    <button class="nav-btn" data-nav="-1"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640"><path d="M201.4 297.4C188.9 309.9 188.9 330.2 201.4 342.7L361.4 502.7C373.9 515.2 394.2 515.2 406.7 502.7C419.2 490.2 419.2 469.9 406.7 457.4L269.3 320L406.6 182.6C419.1 170.1 419.1 149.8 406.6 137.3C394.1 124.8 373.8 124.8 361.3 137.3L201.3 297.3z"/></svg></button>
                    <span class="nav-title">${state.targetDate.toLocaleString('default', { month: 'short', year: 'numeric' })}</span>
                    <button class="nav-btn" data-nav="1"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640"><path d="M439.1 297.4C451.6 309.9 451.6 330.2 439.1 342.7L279.1 502.7C266.6 515.2 246.3 515.2 233.8 502.7C221.3 490.2 221.3 469.9 233.8 457.4L371.2 320L233.9 182.6C221.4 170.1 221.4 149.8 233.9 137.3C246.4 124.8 266.7 124.8 279.2 137.3L439.2 297.3z"/></svg></button>
                `;
            } else if (state.view === 'week') {
                const startOfWeek = new Date(state.targetDate);
                startOfWeek.setDate(startOfWeek.getDate() - (startOfWeek.getDay() + 6) % 7);
                const endOfWeek = new Date(startOfWeek);
                endOfWeek.setDate(startOfWeek.getDate() + 6);
                navHTML = `
                    <button class="nav-btn" data-nav="-7"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640"><path d="M201.4 297.4C188.9 309.9 188.9 330.2 201.4 342.7L361.4 502.7C373.9 515.2 394.2 515.2 406.7 502.7C419.2 490.2 419.2 469.9 406.7 457.4L269.3 320L406.6 182.6C419.1 170.1 419.1 149.8 406.6 137.3C394.1 124.8 373.8 124.8 361.3 137.3L201.3 297.3z"/></svg></button>
                    <span class="nav-title">${startOfWeek.toLocaleDateString(undefined, { month: 'short', day: 'numeric' })} - ${endOfWeek.toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}</span>
                    <button class="nav-btn" data-nav="7"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640"><path d="M439.1 297.4C451.6 309.9 451.6 330.2 439.1 342.7L279.1 502.7C266.6 515.2 246.3 515.2 233.8 502.7C221.3 490.2 221.3 469.9 233.8 457.4L371.2 320L233.9 182.6C221.4 170.1 221.4 149.8 233.9 137.3C246.4 124.8 266.7 124.8 279.2 137.3L439.2 297.3z"/></svg></button>
                `;
            }

            container.innerHTML = `
                <div class="onigiri-heatmap-header">
                    <div class="header-left">
                        <h3>Activity</h3>
                        <div class="heatmap-nav">${navHTML}</div>
                    </div>
                    <div class="header-right">
                        ${streakHTML}
                        <div class="heatmap-filters">
                            <button class="filter-btn ${state.view === 'year' ? 'active' : ''}" data-view="year">Year</button>
                            <button class="filter-btn ${state.view === 'month' ? 'active' : ''}" data-view="month">Month</button>
                            <button class="filter-btn ${state.view === 'week' ? 'active' : ''}" data-view="week">Week</button>
                        </div>
                    </div>
                </div>
                <div class="heatmap-grid"></div>
            `;

            const gridContainer = container.querySelector('.heatmap-grid');
            if (state.view === 'year') {
                drawYearView(gridContainer, preparedData, config);
            } else if (state.view === 'month') {
                drawMonthView(gridContainer, preparedData, config);
            } else if (state.view === 'week') {
                drawWeekView(gridContainer, preparedData, config);
            }

            container.querySelector('.heatmap-filters').addEventListener('click', (e) => {
                if (e.target.classList.contains('filter-btn')) {
                    state.view = e.target.dataset.view;
                    state.targetDate = new Date();
                    draw();
                }
            });

            container.querySelector('.heatmap-nav').addEventListener('click', (e) => {
                const navBtn = e.target.closest('.nav-btn');
                if (navBtn) {
                    const navAmount = parseInt(navBtn.dataset.nav, 10);
                    if (state.view === 'year') {
                        state.targetDate.setFullYear(state.targetDate.getFullYear() + navAmount);
                    } else if (state.view === 'month') {
                        state.targetDate.setMonth(state.targetDate.getMonth() + navAmount);
                    } else if (state.view === 'week') {
                        state.targetDate.setDate(state.targetDate.getDate() + navAmount);
                    }
                    draw();
                }
            });
        }

        draw();
    };

})(window.KaizenHeatmap);